"use client";

import { useState } from "react";
import Link from "next/link";
import LogoMarquee from "@/components/LogoMarquee";
import "./about.css";

const instagram = "https://www.instagram.com/afropeanbusinessnetwork/";
const founderInstagram = "https://www.instagram.com/harmonieessome/";

// Official Brand Color Architecture extracted from ABCN identity & emblem
const brandPalette = [
  {
    name: "Forest Velvet Green",
    hex: "#004F1E",
    role: "African Heritage & Rooted Resilience",
    desc: "Symbolizes fertile ground, continuous growth, ancestral heritage, and grounded communal strength across the continent and diaspora.",
  },
  {
    name: "Continental Horizon Blue",
    hex: "#02318B",
    role: "European Union & Cross-Border Alliances",
    desc: "Reflects transatlantic trust, institutional integrity, strategic enterprise networks, and open horizons connecting Europe and Africa.",
  },
  {
    name: "Radiant Gold / Amber",
    hex: "#E09000",
    role: "Diaspora Prosperity & Innovation",
    desc: "Represents economic empowerment, visionary leadership, tech brilliance, and the transformative capital generated by Afropean founders.",
  },
  {
    name: "Terracotta Crimson Red",
    hex: "#B01010",
    role: "Vitality, Culture & Pan-African Spirit",
    desc: "Celebrates the heartbeat of creative expression, courage, historic solidarity, and the vibrant passion of diaspora communities.",
  },
];

// Verified FAQ items directly from Page 4 of the official ABCN presentation PDF
const faqItems = [
  {
    number: "01",
    question: "What is Afropean Business and Culture Network (ABCN)?",
    answer:
      "ABCN is a platform focused on bridging the gap between African and European communities through business, culture, networking, and collaboration.",
    highlight: "Bridging African & European communities",
    category: "Identity",
    details:
      "Operating from Frankfurt am Main with corridors across major European and African hubs, ABCN dissolves traditional silos between creative expression and commercial enterprise.",
  },
  {
    number: "02",
    question: "Who is ABCN for?",
    answer:
      "ABCN is for entrepreneurs, professionals, creatives, organisations, and diaspora communities looking to connect, collaborate, and grow across African and European spaces.",
    highlight: "Entrepreneurs, creatives & diaspora leaders",
    category: "Audience",
    details:
      "Whether you are an early-stage founder scaling cross-border, a creative sharing African narratives, an executive in European tech, or an institution seeking diaspora engagement, ABCN provides your room.",
  },
  {
    number: "03",
    question: "What is ABCN’s mission?",
    answer:
      "Our mission is to elevate Afropean communities by celebrating culture, increasing business visibility, and fostering meaningful cross-cultural connections.",
    highlight: "Elevating communities & cross-cultural connection",
    category: "Mission",
    details:
      "We achieve this through high-impact cohort initiatives like FIALI, corporate matchmaking, digital innovation toolkits, and curated cultural salons.",
  },
];

export default function AboutPage() {
  const [activeTab, setActiveTab] = useState<string>("All");

  const filteredFaqs =
    activeTab === "All"
      ? faqItems
      : faqItems.filter((item) => item.category === activeTab);

  return (
    <main className="about-page">
      {/* Sticky Header Navigation */}
      <header className="about-nav">
        <Link href="/" className="about-brand" aria-label="ABCN home">
          <img
            src="/assets/abcn/abcn-logo.png"
            alt="ABCN Logo"
            className="about-brand-logo"
          />
          <div className="about-brand-text">
            <span className="about-brand-name">ABCN</span>
            <span className="about-brand-sub">Afropean Business &amp; Culture Network</span>
          </div>
        </Link>

        <nav className="about-navlinks">
          <Link href="/">Home</Link>
          <Link href="/about" className="active">About</Link>
          <Link href="/events">Events</Link>
          <Link href="/#founder">Founder</Link>
          <Link href="/#network">Network</Link>
        </nav>

        <a
          href={instagram}
          target="_blank"
          rel="noreferrer"
          className="about-nav-cta"
        >
          Join network →
        </a>
      </header>

      {/* Hero Section with Official ABCN Definition */}
      <section className="about-hero">
        <div>
          <div className="hero-pill">
            <span className="hero-pill-dot" />
            ABOUT US · AFROPEAN BUSINESS &amp; CULTURE NETWORK
          </div>

          <h1>
            Elevating Afropean communities through <em>culture, business &amp; connection.</em>
          </h1>

          <div className="hero-statement-card">
            <p>
              &ldquo;Afropean Business and Culture Networks is an inclusive platform
              dedicated to elevating Afropean diaspora communities by celebrating their
              cultures and connecting their businesses, fostering visibility, opportunity,
              and cross-cultural collaboration. 🌍&rdquo;
            </p>
          </div>

          <div style={{ display: "flex", gap: "16px", flexWrap: "wrap" }}>
            <a
              href="#mandates"
              style={{
                background: "var(--brand-forest, #004f1e)",
                color: "#fff",
                padding: "13px 26px",
                borderRadius: "999px",
                fontSize: "0.72rem",
                fontWeight: 800,
                letterSpacing: "0.12em",
                textTransform: "uppercase",
              }}
            >
              The Three Mandates ↓
            </a>
            <a
              href="#visionary"
              style={{
                background: "transparent",
                color: "var(--ink)",
                border: "1px solid rgba(0, 79, 30, 0.3)",
                padding: "13px 26px",
                borderRadius: "999px",
                fontSize: "0.72rem",
                fontWeight: 700,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
              }}
            >
              Meet the visionary →
            </a>
          </div>
        </div>

        {/* Official Brand Emblem Card */}
        <div className="hero-emblem-container">
          <div className="emblem-halo" />
          <div className="hero-emblem-card">
            <img
              src="/assets/abcn/abcn-emblem.png"
              alt="Official ABCN Brand Emblem"
              className="hero-emblem-img"
            />
            <div className="emblem-title">ABCN Global Emblem</div>
            <div className="emblem-sub">Frankfurt am Main · Europe · Africa</div>
            <p
              style={{
                fontSize: "0.82rem",
                color: "#55625c",
                lineHeight: 1.5,
                marginTop: "12px",
                marginBottom: 0,
              }}
            >
              The interlinked geometric ribbons represent dynamic corridors between the African continent and European economic centers.
            </p>
          </div>
        </div>
      </section>

      {/* The Three Strategic Mandates (Core Purpose from PDF Page 1 & 3) */}
      <section id="mandates" className="mandates-section">
        <div className="mandates-head">
          <span>THE THREE PILLARS OF ABCN</span>
          <h2>Deconstructing our <em>purpose.</em></h2>
          <p>
            The mission statement outlines three non-negotiable commitments that guide every cohort, salon, and partnership we forge.
          </p>
        </div>

        <div className="mandates-grid">
          <div className="mandate-card">
            <span className="mandate-no">01</span>
            <h3>Celebrating Culture</h3>
            <p>
              Afropean identity is rich and multilayered. We make space for heritage, contemporary arts, language, music, food, and lived experiences without translation or dilution.
            </p>
            <span className="mandate-tagline">HERITAGE · EXPRESSION · BELONGING</span>
          </div>

          <div className="mandate-card">
            <span className="mandate-no">02</span>
            <h3>Connecting Businesses</h3>
            <p>
              Building tangible economic bridges. We connect African startups and diaspora operators with European enterprises, go-to-market systems, and international commercial corridors.
            </p>
            <span className="mandate-tagline">COMMERCE · SAAS · CROSS-BORDER CAPITAL</span>
          </div>

          <div className="mandate-card">
            <span className="mandate-no">03</span>
            <h3>Fostering Visibility &amp; Opportunity</h3>
            <p>
              Elevating diaspora leaders to executive boardrooms, institutional stages, and venture rooms. We turn diaspora potential into lasting economic impact and systemic opportunities.
            </p>
            <span className="mandate-tagline">LEADERSHIP · ALLIANCES · SCALE</span>
          </div>
        </div>
      </section>

      {/* Official FAQ Section (PDF Page 4) */}
      <section id="faq" className="faq-section">
        <div className="faq-container">
          <div className="faq-head">
            <div>
              <span className="section-label-light">FOUNDATIONAL FAQ · THE THREE QUESTIONS</span>
              <h2>Clear answers on <em>what we build.</em></h2>
            </div>
            <p>
              Straight from the founding document: the core definition of ABCN, who it serves, and our driving mission.
            </p>
          </div>

          {/* Interactive Filter Tabs */}
          <div className="faq-tabs">
            {["All", "Identity", "Audience", "Mission"].map((tab) => (
              <button
                key={tab}
                className={"faq-tab-btn " + (activeTab === tab ? "active" : "")}
                onClick={() => setActiveTab(tab)}
              >
                {tab}
              </button>
            ))}
          </div>

          <div className="faq-grid">
            {filteredFaqs.map((item) => (
              <div key={item.number} className="faq-card highlighted">
                <span className="faq-num">{item.number}</span>
                <h3 className="faq-question">{item.question}</h3>
                <p className="faq-answer">{item.answer}</p>
                <div
                  style={{
                    marginTop: "20px",
                    paddingTop: "16px",
                    borderTop: "1px solid rgba(255,255,255,0.08)",
                    fontSize: "0.82rem",
                    color: "rgba(255,255,255,0.6)",
                    lineHeight: 1.5,
                  }}
                >
                  {item.details}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Brand Identity & Color Architecture Showcase */}
      <section className="brand-identity-section">
        <div className="identity-header">
          <span
            style={{
              fontSize: "0.65rem",
              letterSpacing: "0.22em",
              textTransform: "uppercase",
              color: "var(--brand-forest, #004f1e)",
              fontWeight: 800,
              display: "block",
            }}
          >
            BRAND IDENTITY &amp; PALETTE ARCHITECTURE
          </span>
          <h2>The colors of <em>Afropean momentum.</em></h2>
          <p>
            Extracted directly from the official ABCN brand emblem. Each hue encapsulates a vital current of the Afro-European bridge.
          </p>
        </div>

        <div className="palette-grid">
          {brandPalette.map((color) => (
            <div key={color.hex} className="color-swatch-card">
              <div
                className="color-swatch-fill"
                style={{ backgroundColor: color.hex }}
              >
                <span className="color-swatch-hex">{color.hex}</span>
              </div>
              <div className="color-swatch-info">
                <div className="color-swatch-name">{color.name}</div>
                <div
                  style={{
                    fontSize: "0.68rem",
                    fontWeight: 800,
                    textTransform: "uppercase",
                    letterSpacing: "0.1em",
                    color: "var(--brand-forest, #004f1e)",
                    marginBottom: "8px",
                  }}
                >
                  {color.role}
                </div>
                <p className="color-swatch-desc">{color.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Meet the Visionary: Harmonie Essome Spotlight (PDF Page 5 + User Image) */}
      <section id="visionary" className="visionary-section">
        <div className="visionary-container">
          {/* Authentic High-Res Portrait Frame with User-Supplied Image */}
          <div className="visionary-visual">
            <div className="visionary-frame">
              <img
                src="/assets/abcn/harmonie-essome.png"
                alt="Harmonie Essome - Tech CEO & Visionary behind ABCN"
                className="visionary-img"
              />
              <div className="visionary-tagline-overlay">
                <strong>Harmonie Essome</strong>
                <span>Founder &amp; CEO · SoftXcloud GmbH · Creator of ABCN</span>
              </div>
            </div>
          </div>

          {/* Official Bio Copy verbatim from PDF Page 5 */}
          <div className="visionary-copy">
            <span className="visionary-eyebrow">MEET THE VISIONARY · LEADERSHIP DOSSIER</span>
            <h2 className="visionary-title">
              Harmonie<br />
              <em>Essome.</em>
            </h2>

            <div className="visionary-quote-box">
              <p>
                &ldquo;Meet the visionary behind ABCN, Harmonie Essome, a Tech CEO, speaker, and Afro-European business networker passionate about building sustainable bridges between African and European communities through business, talent, culture, and innovation. 🌍&rdquo;
              </p>
            </div>

            <p className="visionary-bio-text">
              As the Founder &amp; CEO of <strong>SoftXcloud GmbH</strong> (Frankfurt am Main) and creator of multiple Afro-European initiatives, her vision is centered on transforming diaspora potential into long-term economic impact, workforce opportunities, and meaningful cross-cultural collaboration.
            </p>

            <p className="visionary-bio-text" style={{ marginTop: "-16px" }}>
              Serving on the advisory board of the <strong>Cameroon International Tech Summit (CITS26)</strong> and pioneering the concept of <em>&ldquo;workpreneurship&rdquo;</em>, Harmonie connects complex enterprise sales engines with global diaspora talent.
            </p>

            <div className="visionary-badges">
              <div className="badge-item">
                <span className="badge-label">Executive Role</span>
                <span className="badge-val">CEO, SoftXcloud GmbH</span>
              </div>
              <div className="badge-item">
                <span className="badge-label">Global Summit Advisory</span>
                <span className="badge-val">Board Member, CITS26</span>
              </div>
              <div className="badge-item">
                <span className="badge-label">Headquarters</span>
                <span className="badge-val">Frankfurt am Main, Germany</span>
              </div>
              <div className="badge-item">
                <span className="badge-label">Flagship Cohort</span>
                <span className="badge-val">FIALI Frankfurt 2026</span>
              </div>
            </div>

            <div className="visionary-actions">
              <a
                href={founderInstagram}
                target="_blank"
                rel="noreferrer"
                className="visionary-btn-primary"
              >
                Follow Harmonie Essome →
              </a>
              <Link href="/events/fiali-frankfurt-2026" className="visionary-btn-secondary">
                Explore FIALI 2026 →
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Flagship Initiative Feature: FIALI 2026 */}
      <section className="flagship-callout-section">
        <div className="flagship-card">
          <div>
            <span className="flagship-kicker">FLAGSHIP INITIATIVE · FRANKFURT 2026</span>
            <h2>Female Innovation Afropean Leadership Initiative</h2>
            <p>
              FIALI is ABCN’s premier executive program designed for 10-15 diverse female founders. Spanning an intensive 2-stage Growth Lab and Summit, FIALI provides practical AI toolkits, investor readiness, and €500 × 2 Startup Innovation Grants.
            </p>
            <div style={{ display: "flex", gap: "16px", flexWrap: "wrap" }}>
              <Link
                href="/events/fiali-frankfurt-2026#apply"
                style={{
                  background: "#e2b978",
                  color: "#070908",
                  padding: "12px 24px",
                  borderRadius: "999px",
                  fontWeight: 800,
                  fontSize: "0.72rem",
                  letterSpacing: "0.1em",
                  textTransform: "uppercase",
                }}
              >
                Apply for Founder Cohort →
              </Link>
              <Link
                href="/events/fiali-frankfurt-2026"
                style={{
                  color: "#ffffff",
                  padding: "12px 24px",
                  borderRadius: "999px",
                  fontWeight: 700,
                  fontSize: "0.72rem",
                  letterSpacing: "0.1em",
                  textTransform: "uppercase",
                  border: "1px solid rgba(255,255,255,0.2)",
                }}
              >
                Full Programme Details
              </Link>
            </div>
          </div>

          <div
            style={{
              background: "rgba(255,255,255,0.04)",
              borderRadius: "20px",
              padding: "28px",
              border: "1px solid rgba(255,255,255,0.08)",
            }}
          >
            <div style={{ fontSize: "0.68rem", color: "#e2b978", letterSpacing: "0.14em", textTransform: "uppercase", fontWeight: 800, marginBottom: "16px" }}>
              COHORT HIGHLIGHTS
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
              <div>
                <strong style={{ fontSize: "1.8rem", color: "#fff", display: "block", fontWeight: 850 }}>10-15</strong>
                <span style={{ fontSize: "0.75rem", color: "rgba(255,255,255,0.6)" }}>Selected founders</span>
              </div>
              <div>
                <strong style={{ fontSize: "1.8rem", color: "#e2b978", display: "block", fontWeight: 850 }}>€1,000</strong>
                <span style={{ fontSize: "0.75rem", color: "rgba(255,255,255,0.6)" }}>Grant pool</span>
              </div>
              <div>
                <strong style={{ fontSize: "1.8rem", color: "#fff", display: "block", fontWeight: 850 }}>2 Stages</strong>
                <span style={{ fontSize: "0.75rem", color: "rgba(255,255,255,0.6)" }}>Lab + Summit</span>
              </div>
              <div>
                <strong style={{ fontSize: "1.8rem", color: "#7ee0be", display: "block", fontWeight: 850 }}>AI Tools</strong>
                <span style={{ fontSize: "0.75rem", color: "rgba(255,255,255,0.6)" }}>Enterprise systems</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Community in Motion: Authentic Photography */}
      <section className="ecosystem-gallery-section">
        <div style={{ textAlign: "center", maxWidth: "680px", margin: "0 auto" }}>
          <span
            style={{
              fontSize: "0.65rem",
              letterSpacing: "0.22em",
              textTransform: "uppercase",
              color: "var(--brand-forest, #004f1e)",
              fontWeight: 800,
              display: "block",
            }}
          >
            COMMUNITY IN MOTION
          </span>
          <h2 style={{ fontSize: "2.4rem", letterSpacing: "-0.04em", margin: "10px 0 14px" }}>
            Where ambition meets <em>shared culture.</em>
          </h2>
          <p style={{ color: "#55625c", fontSize: "0.95rem", lineHeight: 1.6 }}>
            Our gatherings across Frankfurt and diaspora corridors fuse executive discipline with cultural belonging.
          </p>
        </div>

        <div className="gallery-grid">
          <div className="gallery-item large">
            <img
              src="/assets/abcn/innovators-summit.jpg"
              alt="Afropean female founders collaborating during Frankfurt innovation summit"
            />
            <div className="gallery-overlay">
              <span className="gallery-tag">PAN-AFRICAN &amp; EUROPEAN SUMMITS</span>
              <h3 className="gallery-title">Elevating Diaspora Innovators Across Borders</h3>
            </div>
          </div>

          <div className="gallery-item">
            <img
              src="/assets/abcn/collaborators.png"
              alt="Founders in session during the Frankfurt Founder Lab"
            />
            <div className="gallery-overlay">
              <span className="gallery-tag">FOUNDER GROWTH LABS</span>
              <h3 className="gallery-title">Intimate Cohorts &amp; Scalable Playbooks</h3>
            </div>
          </div>

          <div className="gallery-item">
            <img
              src="/assets/abcn/ecosystem-network.png"
              alt="Ecosystem network and cultural salons"
            />
            <div className="gallery-overlay">
              <span className="gallery-tag">CULTURAL SALONS</span>
              <h3 className="gallery-title">Connecting Creative Voices &amp; Capital</h3>
            </div>
          </div>
        </div>
      </section>

      {/* Partner Logo Marquee (100% Transparent Background) */}
      <section style={{ padding: "40px 0 60px" }}>
        <LogoMarquee
          theme="light"
          speed="slow"
          label="Institutional &amp; Ecosystem Collaborators"
          tagline="Frankfurt · Europe · Africa"
        />
      </section>

      {/* Invitation Call to Action */}
      <section
        style={{
          background: "linear-gradient(135deg, #004f1e 0%, #070b11 100%)",
          color: "#fff",
          padding: "85px 5vw",
          textAlign: "center",
        }}
      >
        <div style={{ maxWidth: "720px", margin: "0 auto" }}>
          <span
            style={{
              fontSize: "0.65rem",
              letterSpacing: "0.22em",
              textTransform: "uppercase",
              color: "#e2b978",
              fontWeight: 800,
              display: "block",
              marginBottom: "14px",
            }}
          >
            ENTER THE NETWORK
          </span>
          <h2 style={{ fontSize: "2.7rem", letterSpacing: "-0.03em", margin: "0 0 20px" }}>
            The living bridge is built by people.
          </h2>
          <p
            style={{
              fontSize: "1.05rem",
              lineHeight: 1.65,
              color: "rgba(255,255,255,0.8)",
              marginBottom: "36px",
            }}
          >
            Whether scaling a cross-border venture, contributing cultural insight, or partnering institutionally - your presence moves the room.
          </p>
          <div style={{ display: "flex", justifyContent: "center", gap: "16px", flexWrap: "wrap" }}>
            <Link
              href="/events/fiali-frankfurt-2026#apply"
              style={{
                background: "#e2b978",
                color: "#070908",
                padding: "14px 30px",
                borderRadius: "999px",
                fontWeight: 800,
                fontSize: "0.75rem",
                letterSpacing: "0.1em",
                textTransform: "uppercase",
              }}
            >
              Apply to FIALI 2026 →
            </Link>
            <a
              href={instagram}
              target="_blank"
              rel="noreferrer"
              style={{
                background: "rgba(255,255,255,0.1)",
                color: "#fff",
                border: "1px solid rgba(255,255,255,0.25)",
                padding: "14px 30px",
                borderRadius: "999px",
                fontWeight: 700,
                fontSize: "0.75rem",
                letterSpacing: "0.1em",
                textTransform: "uppercase",
              }}
            >
              Connect on Instagram
            </a>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer
        style={{
          background: "#070b11",
          color: "rgba(255,255,255,0.6)",
          padding: "44px 5vw",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "20px",
          fontSize: "0.75rem",
          borderTop: "1px solid rgba(255,255,255,0.08)",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <img
            src="/assets/abcn/abcn-emblem.png"
            alt="ABCN Emblem"
            style={{ width: "24px", height: "24px" }}
          />
          <span style={{ fontWeight: 800, color: "#fff", letterSpacing: "0.05em" }}>
            ABCN © 2026
          </span>
          <span>· Afropean Business &amp; Culture Network</span>
        </div>
        <div style={{ display: "flex", gap: "24px" }}>
          <Link href="/" style={{ color: "#fff" }}>Home</Link>
          <Link href="/about" style={{ color: "#e2b978" }}>About</Link>
          <Link href="/events" style={{ color: "#fff" }}>Events</Link>
          <a href={instagram} target="_blank" rel="noreferrer" style={{ color: "#fff" }}>
            Instagram
          </a>
        </div>
      </footer>
    </main>
  );
}
